### ISSUE TITLE
Bugs when "Starting online simulation"

### ISSUE THREAD

**Issue by WHYwyh** [losonczylab/CA3_replay#1]
Hello, I'm very interested in your work and currently trying to reproduce the experiments. I git clone the repo and it turned out that the released code have some bugs to when "Starting online simulation". I have tried a lot to fix it but it's quite hard for me as a brian2 beginner, could you please help me with that, thanks a lot! 

And here is the whole log:

~/CA3_replay/ca3spiking$ python run_simulation.py 
[2024-11-03 23:40:52,527][INFO]: Connecting djuser@localhost:3306
[2024-11-03 23:40:52,569][INFO]: Connected djuser@localhost:3306
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9000/9000 [00:08<00:00, 1022.13it/s]
21930 spikes deleted becuse of too short refractory period
43 spikes deleted becuse of too short refractory period
33 spikes deleted becuse of too short refractory period
30 spikes deleted becuse of too short refractory period
33 spikes deleted becuse of too short refractory period
45 spikes deleted becuse of too short refractory period
50 spikes deleted becuse of too short refractory period
32 spikes deleted becuse of too short refractory period
46 spikes deleted becuse of too short refractory period
42 spikes deleted becuse of too short refractory period
34 spikes deleted becuse of too short refractory period
41 spikes deleted becuse of too short refractory period
43 spikes deleted becuse of too short refractory period
47 spikes deleted becuse of too short refractory period
47 spikes deleted becuse of too short refractory period
36 spikes deleted becuse of too short refractory period
40 spikes deleted becuse of too short refractory period
49 spikes deleted becuse of too short refractory period
43 spikes deleted becuse of too short refractory period
38 spikes deleted becuse of too short refractory period
44 spikes deleted becuse of too short refractory period
42 spikes deleted becuse of too short refractory period
43 spikes deleted becuse of too short refractory period
56 spikes deleted becuse of too short refractory period
35 spikes deleted becuse of too short refractory period
39 spikes deleted becuse of too short refractory period
42 spikes deleted becuse of too short refractory period
34 spikes deleted becuse of too short refractory period
55 spikes deleted becuse of too short refractory period
37 spikes deleted becuse of too short refractory period
57 spikes deleted becuse of too short refractory period
60 spikes deleted becuse of too short refractory period
36 spikes deleted becuse of too short refractory period
40 spikes deleted becuse of too short refractory period
39 spikes deleted becuse of too short refractory period
33 spikes deleted becuse of too short refractory period
47 spikes deleted becuse of too short refractory period
44 spikes deleted becuse of too short refractory period
47 spikes deleted becuse of too short refractory period
41 spikes deleted becuse of too short refractory period
48 spikes deleted becuse of too short refractory period
34 spikes deleted becuse of too short refractory period
37 spikes deleted becuse of too short refractory period
38 spikes deleted becuse of too short refractory period
43 spikes deleted becuse of too short refractory period
50 spikes deleted becuse of too short refractory period
59 spikes deleted becuse of too short refractory period
42 spikes deleted becuse of too short refractory period
49 spikes deleted becuse of too short refractory period
50 spikes deleted becuse of too short refractory period
44 spikes deleted becuse of too short refractory period
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 663.71it/s]
37 spikes deleted becuse of too short refractory period

Starting online simulation...
using i->e plasticity
using E->I plasticity
ERROR      Brian 2 encountered an unexpected error. If you think this is a bug in Brian 2, please report this issue either to the discourse forum at <http://brian.discourse.group/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_1tctbtr3.log  Additionally, you can also include a copy of the script that was run, available at: /tmp/brian_script_dyfq0d0u.py Thanks! [brian2]
Traceback (most recent call last):
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/parsing/rendering.py", line 64, in render_node
    return getattr(self, methname)(node)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/parsing/rendering.py", line 101, in render_Call
    if node.func.id in self.auto_vectorise:
AttributeError: 'Attribute' object has no attribute 'id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/core/network.py", line 1002, in before_run
    obj.before_run(run_namespace)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/core/base.py", line 335, in device_override_decorated_function
    return func(*args, **kwds)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/synapses/synapses.py", line 366, in before_run
    super().before_run(run_namespace)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/groups/group.py", line 1266, in before_run
    self.create_code_objects(run_namespace)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/synapses/synapses.py", line 394, in create_code_objects
    weakref.proxy(self.create_default_code_object(run_namespace)),
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/groups/group.py", line 1240, in create_default_code_object
    self.codeobj = create_runner_codeobj(
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/codegen/codeobject.py", line 484, in create_runner_codeobj
    return device.code_object(
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/devices/cpp_standalone/device.py", line 704, in code_object
    codeobj = super().code_object(
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/devices/device.py", line 324, in code_object
    scalar_code, vector_code, kwds = generator.translate(
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/codegen/generators/base.py", line 303, in translate
    translated = self.translate_statement_sequence(
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/codegen/generators/cpp_generator.py", line 419, in translate_statement_sequence
    lines += self.translate_to_statements(stmts, cond_write)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/codegen/generators/cpp_generator.py", line 345, in translate_to_statements
    line = self.translate_statement(stmt)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/codegen/generators/cpp_generator.py", line 311, in translate_statement
    code = f"{decl + var} {op} {self.translate_expression(expr)};"
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/codegen/generators/cpp_generator.py", line 252, in translate_expression
    CPPNodeRenderer(auto_vectorise=self.auto_vectorise)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/parsing/rendering.py", line 58, in render_expr
    return self.render_node(node.body)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/parsing/rendering.py", line 64, in render_node
    return getattr(self, methname)(node)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/parsing/rendering.py", line 333, in render_BinOp
    return f"1.0f*{self.render_element_parentheses(node.left)}/{self.render_element_parentheses(node.right)}"
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/parsing/rendering.py", line 119, in render_element_parentheses
    return self.render_node(node)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/parsing/rendering.py", line 78, in render_node
    raise SyntaxError(
SyntaxError: Brian equations/expressions do not support the 'Call' syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "CA3_replay/ca3spiking/run_simulation.py", line 489, in <module>
    weights.populate()
  File ".conda/envs/brian2/lib/python3.9/site-packages/datajoint/autopopulate.py", line 254, in populate
    status = self._populate1(key, jobs, **populate_kwargs)
  File ".conda/envs/brian2/lib/python3.9/site-packages/datajoint/autopopulate.py", line 322, in _populate1
    make(dict(key), **(make_kwargs or {}))
  File "CA3_replay/ca3spiking/run_simulation.py", line 210, in make
    weightmx, in_weight_mx, pc_in_weight_mx = learning_with_interneurons(spiking_neurons, spike_times,
  File ".conda/envs/brian2/lib/python3.9/site-packages/ca3spiking/stdp.py", line 138, in learning_with_interneurons
    run(time*second, report="text")
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/units/fundamentalunits.py", line 2652, in new_f
    result = f(*args, **kwds)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/core/magic.py", line 407, in run
    return magic_network.run(
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/core/magic.py", line 248, in run
    Network.run(
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/core/base.py", line 333, in device_override_decorated_function
    return getattr(curdev, name)(*args, **kwds)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/devices/cpp_standalone/device.py", line 1814, in network_run
    net.before_run(namespace)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/core/base.py", line 335, in device_override_decorated_function
    return func(*args, **kwds)
  File ".conda/envs/brian2/lib/python3.9/site-packages/brian2/core/network.py", line 1004, in before_run
    raise BrianObjectException(
brian2.core.base.BrianObjectException: Error encountered with object named 'synapses_1_pre'.
Object was created here (most recent call only, full details in debug log):
  File '.conda/envs/brian2/lib/python3.9/site-packages/ca3spiking/stdp.py', line 90, in learning_with_interneurons
    IN_STDP = Synapses(IN, PC,

An error occurred when preparing an object. (See above for original error message and traceback.)

**Comment by WHYwyh** [comment]
It has been fixed. I found it was caused by my brian2 not being installed correctly.

**Comment by WHYwyh** [comment]
It has been fixed. I found it was caused by my brian2 not being installed correctly.
